### ISSUE TITLE
Compatibility with linenos

### ISSUE THREAD

**Issue by NathanHazout** [iwootten/jekyll-syntax#1]
Are you stylesheets compatible with the `linenos` option?

When I try them with this option, it creates a table, and it looks horrible.

I use Jekyll 3 with Rouge.

**Comment by iwootten** [comment]
The stylesheets are just straight output from pygmentize, any other options you'd need should be specified using the command detailed in the readme and any other options pygments details in [their docs](http://pygments.org/docs/formatters/)

**Comment by NathanHazout** [comment]
Let me clarify.
1. Create a Jekyll 3.0 project (or Jekyll 2 actually, I tried both).
2. Add one of your generated syntax CSS files
3. Create a code snippet using:

```
{% highlight javascript lineos %}
blabla
blabla
blabla
{% endhighlight %}
```

You will see the line numbers appear completely messed up.
